# Generated by Django 5.1.2 on 2024-11-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0003_livro_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos', to='app_biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lidos',
            field=models.ManyToManyField(blank=True, related_name='lidos', to='app_biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proximas_leituras',
            field=models.ManyToManyField(blank=True, related_name='proximas_leituras', to='app_biblioteca.livro'),
        ),
    ]
