# Generated by Django 5.1.1 on 2024-11-19 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0004_usuario_favoritos_usuario_lidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.usuario')),
            ],
        ),
    ]
