# Generated by Django 5.1.2 on 2024-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='link_livro',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
